version: '3.8'

x-app:
  &app
  build:
    args:
      RUBY_VERSION: 3.1.0
    context: .
  depends_on:
    - db
    - redis
  stdin_open: true
  tty: true
  volumes:
    - .:/srv/app
    - bundle:/usr/local/bundle
    - type: tmpfs
      target: /srv/app/tmp/pids/

services:
  db:
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

  web:
    <<: *app
    command: bin/dev
    ports:
      - '3000:3000'

volumes:
  bundle: null
  postgres: null
  redis: null
